"""added quantity to cart_product

Revision ID: 2087a5477f55
Revises: 9d088074672d
Create Date: 2024-11-12 00:29:46.981592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2087a5477f55'
down_revision = '9d088074672d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
