"""added seller_id column to products

Revision ID: 563de94be25e
Revises: 6cfe8675f70a
Create Date: 2024-11-15 19:17:24.522317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563de94be25e'
down_revision = '6cfe8675f70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
