name: CI

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
 test:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'
  - name: Install dependencies
    run: |
      cd server
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  - name: Setup .env file
    run: |
      touch .env
      echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> .env
  - name: Test with pytest
    run: |
      pip install pytest
      pytest
